import type { Atom } from './types';

export const ATOMS: Record<string, Atom> = {
  H:  { symbol: 'H',  name: '수소',   atomicNumber: 1,  color: '#FFFFFF', radius: 25, electronegativity: 2.20, valenceElectrons: 1 },
  He: { symbol: 'He', name: '헬륨',   atomicNumber: 2,  color: '#D9FFFF', radius: 28, electronegativity: 0,    valenceElectrons: 2 },
  Li: { symbol: 'Li', name: '리튬',   atomicNumber: 3,  color: '#CC80FF', radius: 34, electronegativity: 0.98, valenceElectrons: 1 },
  Be: { symbol: 'Be', name: '베릴륨', atomicNumber: 4,  color: '#C2FF00', radius: 28, electronegativity: 1.57, valenceElectrons: 2 },
  B:  { symbol: 'B',  name: '붕소',   atomicNumber: 5,  color: '#FFB5B5', radius: 30, electronegativity: 2.04, valenceElectrons: 3 },
  C:  { symbol: 'C',  name: '탄소',   atomicNumber: 6,  color: '#909090', radius: 30, electronegativity: 2.55, valenceElectrons: 4 },
  N:  { symbol: 'N',  name: '질소',   atomicNumber: 7,  color: '#3050F8', radius: 28, electronegativity: 3.04, valenceElectrons: 5 },
  O:  { symbol: 'O',  name: '산소',   atomicNumber: 8,  color: '#FF0D0D', radius: 28, electronegativity: 3.44, valenceElectrons: 6 },
  F:  { symbol: 'F',  name: '플루오린', atomicNumber: 9, color: '#90E050', radius: 26, electronegativity: 3.98, valenceElectrons: 7 },
  Ne: { symbol: 'Ne', name: '네온',   atomicNumber: 10, color: '#B3E3F5', radius: 28, electronegativity: 0,    valenceElectrons: 8 },
  Na: { symbol: 'Na', name: '나트륨', atomicNumber: 11, color: '#AB5CF2', radius: 36, electronegativity: 0.93, valenceElectrons: 1 },
  Mg: { symbol: 'Mg', name: '마그네슘', atomicNumber: 12, color: '#8AFF00', radius: 32, electronegativity: 1.31, valenceElectrons: 2 },
  Al: { symbol: 'Al', name: '알루미늄', atomicNumber: 13, color: '#BFA6A6', radius: 32, electronegativity: 1.61, valenceElectrons: 3 },
  Si: { symbol: 'Si', name: '규소',   atomicNumber: 14, color: '#F0C8A0', radius: 32, electronegativity: 1.90, valenceElectrons: 4 },
  P:  { symbol: 'P',  name: '인',     atomicNumber: 15, color: '#FF8000', radius: 30, electronegativity: 2.19, valenceElectrons: 5 },
  S:  { symbol: 'S',  name: '황',     atomicNumber: 16, color: '#FFFF30', radius: 30, electronegativity: 2.58, valenceElectrons: 6 },
  Cl: { symbol: 'Cl', name: '염소',   atomicNumber: 17, color: '#1FF01F', radius: 30, electronegativity: 3.16, valenceElectrons: 7 },
  Ar: { symbol: 'Ar', name: '아르곤', atomicNumber: 18, color: '#80D1E3', radius: 30, electronegativity: 0,    valenceElectrons: 8 },
  K:  { symbol: 'K',  name: '칼륨',   atomicNumber: 19, color: '#8F40D4', radius: 40, electronegativity: 0.82, valenceElectrons: 1 },
  Ca: { symbol: 'Ca', name: '칼슘',   atomicNumber: 20, color: '#3DFF00', radius: 38, electronegativity: 1.00, valenceElectrons: 2 },
  Fe: { symbol: 'Fe', name: '철',     atomicNumber: 26, color: '#E06633', radius: 34, electronegativity: 1.83, valenceElectrons: 2 },
  Cu: { symbol: 'Cu', name: '구리',   atomicNumber: 29, color: '#C88033', radius: 32, electronegativity: 1.90, valenceElectrons: 1 },
  Zn: { symbol: 'Zn', name: '아연',   atomicNumber: 30, color: '#7D80B0', radius: 32, electronegativity: 1.65, valenceElectrons: 2 },
  Ag: { symbol: 'Ag', name: '은',     atomicNumber: 47, color: '#C0C0C0', radius: 34, electronegativity: 1.93, valenceElectrons: 1 },
  Au: { symbol: 'Au', name: '금',     atomicNumber: 79, color: '#FFD123', radius: 34, electronegativity: 2.54, valenceElectrons: 1 },
};

export const ELECTRON_CONFIG: Record<string, number[]> = {
  H:  [1],
  He: [2],
  Li: [2, 1],
  Be: [2, 2],
  B:  [2, 3],
  C:  [2, 4],
  N:  [2, 5],
  O:  [2, 6],
  F:  [2, 7],
  Ne: [2, 8],
  Na: [2, 8, 1],
  Mg: [2, 8, 2],
  Al: [2, 8, 3],
  Si: [2, 8, 4],
  P:  [2, 8, 5],
  S:  [2, 8, 6],
  Cl: [2, 8, 7],
  Ar: [2, 8, 8],
  K:  [2, 8, 8, 1],
  Ca: [2, 8, 8, 2],
};
