import type { Atom } from './types';

export const ATOMS: Record<string, Atom> = {
  // 1주기
  H:  { symbol: 'H',  name: '수소',     atomicNumber: 1,  color: '#FFFFFF', radius: 25, electronegativity: 2.20, valenceElectrons: 1 },
  He: { symbol: 'He', name: '헬륨',     atomicNumber: 2,  color: '#D9FFFF', radius: 28, electronegativity: 0,    valenceElectrons: 2 },
  // 2주기
  Li: { symbol: 'Li', name: '리튬',     atomicNumber: 3,  color: '#CC80FF', radius: 34, electronegativity: 0.98, valenceElectrons: 1 },
  Be: { symbol: 'Be', name: '베릴륨',   atomicNumber: 4,  color: '#C2FF00', radius: 28, electronegativity: 1.57, valenceElectrons: 2 },
  B:  { symbol: 'B',  name: '붕소',     atomicNumber: 5,  color: '#FFB5B5', radius: 30, electronegativity: 2.04, valenceElectrons: 3 },
  C:  { symbol: 'C',  name: '탄소',     atomicNumber: 6,  color: '#909090', radius: 30, electronegativity: 2.55, valenceElectrons: 4 },
  N:  { symbol: 'N',  name: '질소',     atomicNumber: 7,  color: '#3050F8', radius: 28, electronegativity: 3.04, valenceElectrons: 5 },
  O:  { symbol: 'O',  name: '산소',     atomicNumber: 8,  color: '#FF0D0D', radius: 28, electronegativity: 3.44, valenceElectrons: 6 },
  F:  { symbol: 'F',  name: '플루오린', atomicNumber: 9,  color: '#90E050', radius: 26, electronegativity: 3.98, valenceElectrons: 7 },
  Ne: { symbol: 'Ne', name: '네온',     atomicNumber: 10, color: '#B3E3F5', radius: 28, electronegativity: 0,    valenceElectrons: 8 },
  // 3주기
  Na: { symbol: 'Na', name: '나트륨',   atomicNumber: 11, color: '#AB5CF2', radius: 36, electronegativity: 0.93, valenceElectrons: 1 },
  Mg: { symbol: 'Mg', name: '마그네슘', atomicNumber: 12, color: '#8AFF00', radius: 32, electronegativity: 1.31, valenceElectrons: 2 },
  Al: { symbol: 'Al', name: '알루미늄', atomicNumber: 13, color: '#BFA6A6', radius: 32, electronegativity: 1.61, valenceElectrons: 3 },
  Si: { symbol: 'Si', name: '규소',     atomicNumber: 14, color: '#F0C8A0', radius: 32, electronegativity: 1.90, valenceElectrons: 4 },
  P:  { symbol: 'P',  name: '인',       atomicNumber: 15, color: '#FF8000', radius: 30, electronegativity: 2.19, valenceElectrons: 5 },
  S:  { symbol: 'S',  name: '황',       atomicNumber: 16, color: '#FFFF30', radius: 30, electronegativity: 2.58, valenceElectrons: 6 },
  Cl: { symbol: 'Cl', name: '염소',     atomicNumber: 17, color: '#1FF01F', radius: 30, electronegativity: 3.16, valenceElectrons: 7 },
  Ar: { symbol: 'Ar', name: '아르곤',   atomicNumber: 18, color: '#80D1E3', radius: 30, electronegativity: 0,    valenceElectrons: 8 },
  // 4주기
  K:  { symbol: 'K',  name: '칼륨',     atomicNumber: 19, color: '#8F40D4', radius: 40, electronegativity: 0.82, valenceElectrons: 1 },
  Ca: { symbol: 'Ca', name: '칼슘',     atomicNumber: 20, color: '#3DFF00', radius: 38, electronegativity: 1.00, valenceElectrons: 2 },
  Sc: { symbol: 'Sc', name: '스칸듐',   atomicNumber: 21, color: '#E6E6E6', radius: 34, electronegativity: 1.36, valenceElectrons: 2 },
  Ti: { symbol: 'Ti', name: '타이타늄', atomicNumber: 22, color: '#BFC2C7', radius: 34, electronegativity: 1.54, valenceElectrons: 2 },
  V:  { symbol: 'V',  name: '바나듐',   atomicNumber: 23, color: '#A6A6AB', radius: 33, electronegativity: 1.63, valenceElectrons: 2 },
  Cr: { symbol: 'Cr', name: '크로뮴',   atomicNumber: 24, color: '#8A99C7', radius: 33, electronegativity: 1.66, valenceElectrons: 1 },
  Mn: { symbol: 'Mn', name: '망가니즈', atomicNumber: 25, color: '#9C7AC7', radius: 33, electronegativity: 1.55, valenceElectrons: 2 },
  Fe: { symbol: 'Fe', name: '철',       atomicNumber: 26, color: '#E06633', radius: 34, electronegativity: 1.83, valenceElectrons: 2 },
  Co: { symbol: 'Co', name: '코발트',   atomicNumber: 27, color: '#F090A0', radius: 33, electronegativity: 1.88, valenceElectrons: 2 },
  Ni: { symbol: 'Ni', name: '니켈',     atomicNumber: 28, color: '#50D050', radius: 32, electronegativity: 1.91, valenceElectrons: 2 },
  Cu: { symbol: 'Cu', name: '구리',     atomicNumber: 29, color: '#C88033', radius: 32, electronegativity: 1.90, valenceElectrons: 1 },
  Zn: { symbol: 'Zn', name: '아연',     atomicNumber: 30, color: '#7D80B0', radius: 32, electronegativity: 1.65, valenceElectrons: 2 },
  Ga: { symbol: 'Ga', name: '갈륨',     atomicNumber: 31, color: '#C28F8F', radius: 34, electronegativity: 1.81, valenceElectrons: 3 },
  Ge: { symbol: 'Ge', name: '저마늄',   atomicNumber: 32, color: '#668F8F', radius: 34, electronegativity: 2.01, valenceElectrons: 4 },
  As: { symbol: 'As', name: '비소',     atomicNumber: 33, color: '#BD80E3', radius: 32, electronegativity: 2.18, valenceElectrons: 5 },
  Se: { symbol: 'Se', name: '셀레늄',   atomicNumber: 34, color: '#FFA100', radius: 30, electronegativity: 2.55, valenceElectrons: 6 },
  Br: { symbol: 'Br', name: '브로민',   atomicNumber: 35, color: '#A62929', radius: 30, electronegativity: 2.96, valenceElectrons: 7 },
  Kr: { symbol: 'Kr', name: '크립톤',   atomicNumber: 36, color: '#5CB8D1', radius: 32, electronegativity: 3.00, valenceElectrons: 8 },
  // 5주기 (고등 과정에서 자주 등장)
  Rb: { symbol: 'Rb', name: '루비듐',   atomicNumber: 37, color: '#702EB0', radius: 42, electronegativity: 0.82, valenceElectrons: 1 },
  Sr: { symbol: 'Sr', name: '스트론튬', atomicNumber: 38, color: '#00FF00', radius: 40, electronegativity: 0.95, valenceElectrons: 2 },
  Ag: { symbol: 'Ag', name: '은',       atomicNumber: 47, color: '#C0C0C0', radius: 34, electronegativity: 1.93, valenceElectrons: 1 },
  Sn: { symbol: 'Sn', name: '주석',     atomicNumber: 50, color: '#668080', radius: 36, electronegativity: 1.96, valenceElectrons: 4 },
  I:  { symbol: 'I',  name: '아이오딘', atomicNumber: 53, color: '#940094', radius: 32, electronegativity: 2.66, valenceElectrons: 7 },
  Xe: { symbol: 'Xe', name: '제논',     atomicNumber: 54, color: '#429EB0', radius: 34, electronegativity: 2.60, valenceElectrons: 8 },
  // 6주기 (고등 과정에서 자주 등장)
  Ba: { symbol: 'Ba', name: '바륨',     atomicNumber: 56, color: '#00C900', radius: 42, electronegativity: 0.89, valenceElectrons: 2 },
  W:  { symbol: 'W',  name: '텅스텐',   atomicNumber: 74, color: '#2194D6', radius: 34, electronegativity: 2.36, valenceElectrons: 2 },
  Pt: { symbol: 'Pt', name: '백금',     atomicNumber: 78, color: '#D0D0E0', radius: 34, electronegativity: 2.28, valenceElectrons: 1 },
  Au: { symbol: 'Au', name: '금',       atomicNumber: 79, color: '#FFD123', radius: 34, electronegativity: 2.54, valenceElectrons: 1 },
  Hg: { symbol: 'Hg', name: '수은',     atomicNumber: 80, color: '#B8B8D0', radius: 34, electronegativity: 2.00, valenceElectrons: 2 },
  Pb: { symbol: 'Pb', name: '납',       atomicNumber: 82, color: '#575961', radius: 36, electronegativity: 2.33, valenceElectrons: 4 },
};

export const ELECTRON_CONFIG: Record<string, number[]> = {
  H:  [1],
  He: [2],
  Li: [2, 1],
  Be: [2, 2],
  B:  [2, 3],
  C:  [2, 4],
  N:  [2, 5],
  O:  [2, 6],
  F:  [2, 7],
  Ne: [2, 8],
  Na: [2, 8, 1],
  Mg: [2, 8, 2],
  Al: [2, 8, 3],
  Si: [2, 8, 4],
  P:  [2, 8, 5],
  S:  [2, 8, 6],
  Cl: [2, 8, 7],
  Ar: [2, 8, 8],
  K:  [2, 8, 8, 1],
  Ca: [2, 8, 8, 2],
  Sc: [2, 8, 9, 2],
  Ti: [2, 8, 10, 2],
  V:  [2, 8, 11, 2],
  Cr: [2, 8, 13, 1],
  Mn: [2, 8, 13, 2],
  Fe: [2, 8, 14, 2],
  Co: [2, 8, 15, 2],
  Ni: [2, 8, 16, 2],
  Cu: [2, 8, 18, 1],
  Zn: [2, 8, 18, 2],
  Ga: [2, 8, 18, 3],
  Ge: [2, 8, 18, 4],
  As: [2, 8, 18, 5],
  Se: [2, 8, 18, 6],
  Br: [2, 8, 18, 7],
  Kr: [2, 8, 18, 8],
};
